

backend:
  name: git-gateway
  branch: main
 
local_backend: 
  url: http://192.168.0.237:8081/api/v1
  allowed_hosts:
    - 192.168.0.237

publish_mode: editorial_workflow

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "antiques"
    label: "Antiques"
    folder: "src/content/antiques"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Име", name: "title", widget: "string" }

      - { label: "Описание", name: "description", widget: "text" }

      - { label: "Категория", name: "category", id: "category", widget: "select",
          options: ["Антикварни часовници", "Порцелан", "Старинни бижута", "Изобразително изкуство", "Колекционерски предмети","Етника и Фолклор","Книги","Сувенири и Подараци","Военни предмети"] }

      - { label: "Подкатегория", name: "subcategory", widget: "dependent-select", required: false }

      - { label: "Цена", name: "price", widget: "number" }

      - { label: "Препоръчан", "name": "featured", widget: "boolean", default: false, required: false }

      - { label: "Наличен", "name": "available", widget: "boolean", default: true, required: false }

      - { label: "Нов", "name": "new",  widget: "boolean", default: true, required: false }
      
      - { label: "Дата на добавяне", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false, required: false }

      - label: "Снимки"
        name: "images"
        widget: "list"
        min: 1
        required: true 
        add_to_top: true
        summary: "{{fields.url}}" 
        fields:
          - { label: "Снимка", name: "url", widget: "image", required: true }
          - { label: "Описание", name: "caption", widget: "string", required: false }